openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /todos:
    get:
      tags:
      - todo-rest-endpoint
      operationId: getAll
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoListResponse'
    put:
      tags:
      - todo-rest-endpoint
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoRequest'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "204":
          description: No Content
    post:
      tags:
      - todo-rest-endpoint
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "204":
          description: No Content
  /todos/{id}:
    delete:
      tags:
      - todo-rest-endpoint
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "204":
          description: No Content
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    JsonNode:
      type: object
    UpdateTodoRequest:
      required:
      - content
      - id
      - metaData
      - state
      type: object
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
        state:
          type: string
          enum:
          - UNFINISHED
          - FINISHED
        metaData:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/JsonNode'
    CreateTodoRequest:
      required:
      - content
      type: object
      properties:
        content:
          type: string
        metaData:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/JsonNode'
    TodoItemResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
        state:
          type: string
        metaData:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/JsonNode'
    TodoListResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/TodoItemResponse'
